services:
    sortable_behavior.position.orm:
        class: Runroom\SortableBehaviorBundle\Services\ORMPositionHandler
        public: false
        arguments:
            - '@doctrine.orm.entity_manager'
        calls:
            - ['setPositionField', ['%sortable.behavior.position.field%']]
            - ['setSortableGroups', ['%sortable.behavior.sortable_groups%']]

    sortable_behavior.position.odm:
        class: Runroom\SortableBehaviorBundle\Services\ODMPositionHandler
        public: false
        arguments:
            - '@doctrine_mongodb.odm.document_manager'
        calls:
            - ['setPositionField', ['%sortable.behavior.position.field%']]

    sortable_behavior.position.gedmo:
        class: Runroom\SortableBehaviorBundle\Service\GedmoPositionHandler
        public: false
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@stof_doctrine_extensions.listener.sortable'

    sortable_behavior.twig.extension:
        class: Runroom\SortableBehaviorBundle\Twig\ObjectPositionExtension
        public: false
        arguments:
            - '@sortable_behavior.position'
        tags:
            - { name: twig.extension }
